### ISSUE TITLE
option to specify the path to `pdm`

### ISSUE THREAD

**Issue by DetachHead** [pdm-project/update-deps-action#15]
i have pdm pinned and installed within my project [using pyprojectx](https://pdm-project.org/en/latest/#__tabbed_2_6), so it would be nice if i could tell the action to use that version instead of [the one in the `setup-pdm` action](https://github.com/pdm-project/update-deps-action/blob/220b51345905dbf3737390f2db880b10bbf9e530/action.yml#L40C13-L40C34)

something like a `pdm-path` option would be great:

```yaml
jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Update dependencies
        uses: pdm-project/update-deps-action@main
        with:
          pdm-path: .pyprojectx/main/pdm
```
